### ISSUE TITLE
KeyError on Script run

### ISSUE THREAD

**Issue by MoonstarCoding** [danrahn/PlexPlaylistToCollection#1]
Getting following error when attempting to run the script.

```sh
[main 2021-08-02T12:23:19.332Z] window: using vscode-file:// protocol and V8 cache options: bypassHeatCheck
[main 2021-08-02T12:23:19.525Z] update#setState idle
         python .\PlexPlaylistToCollection.py

Available Playlists:

Traceback (most recent call last):
  File "D:\Code\python\PlexPlaylistToCollection\PlexPlaylistToCollection.py", line 382, in <module>
    runner.run()
  File "D:\Code\python\PlexPlaylistToCollection\PlexPlaylistToCollection.py", line 89, in run
    playlist = self.find_playlist()
  File "D:\Code\python\PlexPlaylistToCollection\PlexPlaylistToCollection.py", line 165, in find_playlist
    ret = self.select_playlist(playlists['Metadata'], lambda x: x['title'])
KeyError: 'Metadata'
```

**Comment by danrahn** [comment]
@AstroCoding I can't replicate this, but does the latest update (a92a4c6) fix things for you? It could be the case that you have no video playlists to convert to a collection, so there's no metadata to report.
